from .prompts import (
    DISCHARGE_SUMMARY_PROMPT,
    EMERGENCY_DEPT_PROMPT,
    PROGRESS_NOTE_PROMPT,
    RADIOLOGY_REPORT_PROMPT,
    TELEHEALTH_CONSULT_PROMPT,
    TEMPLATE_MODE_PROMPT
)

from ..models.note_models import NoteType

PROMPTS = {
    NoteType.DISCHARGE_SUMMARY: DISCHARGE_SUMMARY_PROMPT,
    NoteType.EMERGENCY_DEPT: EMERGENCY_DEPT_PROMPT,
    NoteType.PROGRESS_NOTE: PROGRESS_NOTE_PROMPT,
    NoteType.RADIOLOGY_REPORT: RADIOLOGY_REPORT_PROMPT,
    NoteType.TELEHEALTH_CONSULT: TELEHEALTH_CONSULT_PROMPT,
}

__all__ = [
    "PROMPTS",
    "TEMPLATE_MODE_PROMPT",
]
